# To make sure as littel as possible cache is written to the shared mount we use apc and redis (for cache that needs to be shared)

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc
    serializer:
        cache: serializer.mapping.cache.apc

doctrine:
    orm:
        metadata_cache_driver: apc
        query_cache_driver: apc
        result_cache_driver:
            type: redis
            host: '%cache_host%'
            port: '%cache_redis_port%'
